### ISSUE TITLE
AWS UG CookBook Community Meetings

### ISSUE THREAD

**Issue by diego7marques** [global-aws-community/aws-ug-cookbook#4]
## AWS UG CookBook Community Meetings
The proposal of AWS UG CookBook Community Meetings aims to help every AWS UG Leader across the globe to elevate the level of engagement of the community sharing experience with peers and addressing some of the following items:
* Tracking the progress of PR's, Issues and Features of UG CookBook repository
* Ensure a cadence of exchange of experience between UG organizers
~~* Discuss challenges and improvements to the AWS User Groups meetings (e.g. What to do when there is no talks proposal?, How can you communicate effectively with your community?, How to address the lack of sponsors?, How to start a new AWS UG?)~~
~~* Share relevant events and news (e.g. AWS Community Days, announce new AWS User Group Leaders, announce new benefits for AWS UG's)~~

The recommended frequency is biweekly or monthly.

## Target Audience
* AWS UG Leaders and Active Members
~~* AWS Heroes~~
~~* AWS Community Builders~~
~~* AWS UG Speakers (benefit that can be offered to attract more speakers to the User Groups)~~
* AWS employees (with emphasis on AWS Developer Advocates,  Managers of community programs, Active members of Open Source community)

## Requirements
* It must have at least 1 facilitator, that is responsible for guide the meeting and ensure online room, agenda and outputs
* To ensure inclusiveness, the meeting must be carried out at different times each month to ensure that everyone around the world is able to take part
* All the topics should be discussed, despite the number of participants of the meeting (when > 1)
* To ensure inclusiveness, the meetings must be done in English

## Outputs
* Recording of the sessions, so it can be watched by those who were not able to join
* Document with defined agenda and tracking of progress (e.g. https://docs.google.com/document/d/1YdpEVhtyCKvwFtXR7cn1Kn2Xc_tdNskoFnhHmFPbtA4/edit#heading=h.w7l85jeih9j6)

## Tasks to be done
- [x] Define at least 1 or 2 facilitators for the first meeting
- [x] Define the first agenda and spread the word
~~- [ ] Create a communication channel to include the target audience (maybe inside cncf slack to start with? telegram group? discord server?)~~
- [x] Create the template document for agenda
- [x] Create a PR to the cookbook explaining what is the AWS UG CookBook Community Meetings

**Comment by tigpt** [comment]
First of all, thanks @diego7marques for your suggestion, I really like it! Communication is key and this can promote a shorter feedback loop and more communication and actions taken.

How can you support you to get this started? I believe we can start using the AWS UG Leaders and AWS Heroes Slack official slack channel to promote this session.

Do you want to do a dry run before the kickoff? We can assume the facilitators roles for the first sessions to get it started, but then share that this roles are open for other people if someone wants to step up.

Since you have some experience attending this on k8gb, do you want to make very simple template document, we can find a small group like the UG Lisbon Leaders to do the dry run of the meeting zero, and then we move with a solid plan to the meeting 1 already promoting this openly on the existing slack channels.

**Comment by Fabrimonteiro** [comment]
I like the idea of creating this @diego7marques! 

Shall we try to pick topics in advance? To better organize the time. 

Will we have a time frame for this? Is half an hour a good starting point? Or do you think is it more suitable for 1 hour or even more?

**Comment by diego7marques** [comment]
Thanks for the feedbacks @tigpt and @Fabrimonteiro, the proposal of running a dry-run within the AWS UG Lisbon seems like a great idea. Let's try it.

I've created [this document](https://onedrive.live.com/edit?id=A64FB59EAD8638C1!102205&resid=A64FB59EAD8638C1!102205&ithint=file%2cdocx&authkey=!AKfz3lsBo4O96Fg&wdo=2&cid=a64fb59ead8638c1) as draft for the meeting notes. We can update it during our dry-run session.

@Fabrimonteiro, my suggestion for your questions:
_"Shall we try to pick topics in advance?"_  A: Yes, ideally the document above will always have the agenda organized before the session. Maybe, can be a good idea to a scheduled message on slack group like weekly asking if anyone would like to suggest any topic for discussion. If don't, we work with the issues and PR's of that month.

_"Will we have a time frame for this? Is half an hour a good starting point?"_ A: I would say that 30 minutes is enough to start, but we can adjust if we have extra topics for a specific session.

**Comment by tigpt** [comment]
Let's start with once a month and do more often if the demands grow? low commitment, easier to start.

**Comment by diego7marques** [comment]
@tigpt @Fabrimonteiro feels like the ideal moment to run the dry-run, as we are starting to get some traction on the repo (more issues opened 😅). Maybe we can try it this week? 

I've crossed out a few itens of the scope of the meeting and kept only the topics related to the ug cookbook repository, with the idea of starting small and avoid distractions/dispersion about the repository progress. Let start this way and see how it goes from there.

**Comment by tigpt** [comment]
24th (tomorrow) after 15h Lisbon time I'm free.

**Comment by diego7marques** [comment]
First meeting scheduled for today at 5PM (Lisbon Time - UTC+1). I've included on the invite: @tigpt, @Fabrimonteiro, @encinar.

Anyone who wants to participate and contribute, is more than welcome! I'll let the relevant links bellow:

Link of the meeting: https://teams.microsoft.com/l/meetup-join/19%3ameeting_NjVkYTM3NjktMTYwNy00OGE4LWFlMjEtN2ExZGMzNWRjMTdl%40thread.v2/0?context=%7b%22Tid%22%3a%22538a9031-c50a-4bfd-80d8-0bdef0c18b09%22%2c%22Oid%22%3a%227a8ecdc4-78cc-4e5a-b213-2bbb3789beb0%22%7d

Agenda updated: https://onedrive.live.com/edit?id=A64FB59EAD8638C1!102205&resid=A64FB59EAD8638C1!102205&ithint=file%2cdocx&authkey=!AKfz3lsBo4O96Fg&wdo=2&cid=a64fb59ead8638c1

**Comment by tigpt** [comment]
use this own repo to share when the next meeting is on the main readme.md

**Comment by diego7marques** [comment]
I've created the #18 PR with the first version of the meeting page. I've included it into the new `events` folder, that made the most sense to me, but I welcome other suggestions.

After the PR has been merged, the issue is ready to be closed.
